name: cyber

on:
  push:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      if:  github.event_name == 'push' && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
      run: cd riotpot && go build -o bin/ -v
        