name: cyber

on:
  push:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.operating-system }}
    strategy:
    matrix:
      operating-system: [ubuntu-latest, windows-latest]
    steps:

    - name: Enter riotpot directory
      run: cd riotpot

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v