name: cyber

on:
  push:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ CYBER ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14, 1.15, 1.16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

    - name: Test
      run: |
        go mod tidy
        go test -v ./...

    - name: Build
      if:  github.event_name == 'push' && (matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest')
      run: cd riotpot && go build -o bin/ -v

    # Autoreleaser https://goreleaser.com/ci/actions/
    # it MAY need secrets! more: https://docs.github.com/en/actions/reference/encrypted-secrets
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@2
      #if: success() && startswith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: Docker Login
    #  uses: docker/login-action@1
    #  with:
    #    registry: ghcr.io
    #    username: ${{ github.repository_owner }}
    #    password: ${{ secrets.GITHUB_TOKEN }}
        